// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kycecnyektdtlxcfhcjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5Y2Vjbnlla3RkdGx4Y2ZoY2pxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MjAwMTQsImV4cCI6MjA1OTE5NjAxNH0.zsa5KV5g7mabuHAdlV85n1aEMAO8FIG6LB8RE7y7_J0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);